In [41]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import  OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer


In [42]:
df = pd.read_csv("../../../data/crop_recommendation_model_ready_data.csv")
X = df.iloc[:, :-1].values
y = df.iloc[:, -1]

In [43]:
print(X)

[[24.37372951 1.417377049 88.50122951 9.387868852 951 'Full Sun']
 [22.0470082 3.17 75.46786885 9.112786885 951 'Full Sun']
 [21.9325 4.786639344 89.24860656 8.502868852 951 'Full Sun']
 ...
 [23.08268293 3.447317073 82.74276423 8.020325203 951 'Full Sun']
 [23.36780488 5.467723577 86.83382114 7.552195122 951 'Full Sun']
 [24.46589431 1.325853659 88.8198374 8.688455285 951 'Full Sun']]


In [44]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [45]:
ct_X = ColumnTransformer(transformers=[
                                       ("sun_exposure", OrdinalEncoder(), [-1])], remainder="passthrough")
X = ct_X.fit_transform(X)


In [46]:
print(X)

[[0.0 24.37372951 1.417377049 88.50122951 9.387868852 951]
 [0.0 22.0470082 3.17 75.46786885 9.112786885 951]
 [0.0 21.9325 4.786639344 89.24860656 8.502868852 951]
 ...
 [0.0 23.08268293 3.447317073 82.74276423 8.020325203 951]
 [0.0 23.36780488 5.467723577 86.83382114 7.552195122 951]
 [0.0 24.46589431 1.325853659 88.8198374 8.688455285 951]]


In [47]:
print(X)

[[0.0 24.37372951 1.417377049 88.50122951 9.387868852 951]
 [0.0 22.0470082 3.17 75.46786885 9.112786885 951]
 [0.0 21.9325 4.786639344 89.24860656 8.502868852 951]
 ...
 [0.0 23.08268293 3.447317073 82.74276423 8.020325203 951]
 [0.0 23.36780488 5.467723577 86.83382114 7.552195122 951]
 [0.0 24.46589431 1.325853659 88.8198374 8.688455285 951]]


In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [49]:
print(X_test)

[[0.0 24.99422078 0.368896104 86.40025974 9.168246753 733]
 [0.0 26.05366883 2.781298701 79.13266234 9.749285714 101]
 [0.0 23.36384868 6.174210526 90.52164474 7.525723684 1411]
 [0.0 22.00788066 2.994115226 89.86930041 8.962510288 2868]
 [1.0 26.72907895 6.166842105 81.51519737 8.927697368 466]
 [0.0 24.163125 2.302434211 88.70493421 9.137697368 401]
 [0.0 23.82538961 2.76512987 86.21597403 8.814805195 733]
 [0.0 23.13898374 1.092682927 87.98365854 8.377723577 951]
 [0.0 22.0337037 4.364650206 91.44106996 9.173786008 2868]
 [0.0 23.64243506 2.553701299 78.87006494 8.699090909 733]
 [1.0 25.52184211 9.412565789 89.20019737 8.021381579 466]
 [0.0 23.08268293 3.447317073 82.74276423 8.020325203 951]
 [0.0 24.42065789 4.804144737 89.87940789 8.153947368 1411]
 [0.0 22.94340164 3.274262295 79.63229508 8.171229508 951]
 [1.0 23.05743836 6.696164384 88.55120548 7.783753425 807]
 [0.0 24.01817073 1.433577236 87.06276423 8.856585366 951]
 [0.0 24.8337013 2.78025974 77.89831169 8.892987013 1600

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[3:8] = sc.fit_transform(X_train[3:8])
X_test[3:8] = sc.transform(X_test[3:8])

In [51]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [52]:
print(encoder.inverse_transform(classifier.predict(X_test)))

['Tomatoes' 'Onions and shallots' 'Chillies and peppers'
 'Cucumbers and gherkins' 'Beans' 'Cucumbers and gherkins'
 'Cucumbers and gherkins' 'Tomatoes' 'Tea leaves' 'Tomatoes' 'Cloves'
 'Beans' 'Chillies and peppers' 'Beans'
 'Cinnamon and cinnamon-tree flowers' 'Beans' 'Eggplants'
 'Onions and shallots' 'Vanilla' 'Pepper' 'Cucumbers and gherkins'
 'Tomatoes' 'Tomatoes' 'Carrots and turnips' 'Pepper' 'Pepper'
 'Cinnamon and cinnamon-tree flowers' 'Chillies and peppers'
 'Chillies and peppers' 'Eggplants' 'Tea leaves' 'Beans' 'Tomatoes'
 'Tea leaves' 'Potatoes' 'Tomatoes' 'Potatoes' 'Potatoes' 'Cloves'
 'Cinnamon and cinnamon-tree flowers' 'Pepper' 'Vanilla'
 'Cucumbers and gherkins' 'Cucumbers and gherkins' 'Beans'
 'Onions and shallots' 'Eggplants' 'Tea leaves' 'Cucumbers and gherkins'
 'Eggplants' 'Carrots and turnips' 'Tomatoes' 'Tomatoes' 'Vanilla'
 'Leeks and other alliaceous vegetables' 'Carrots and turnips' 'Vanilla'
 'Cloves' 'Beans' 'Pepper' 'Potatoes' 'Chillies and peppers' 

In [53]:
y_actual = encoder.inverse_transform(y_test)
y_pred = encoder.inverse_transform(classifier.predict(X_test))
print(np.concat([y_actual.reshape(-1, 1), y_pred.reshape(-1, 1)], 1))

[['Tomatoes' 'Tomatoes']
 ['Onions and shallots' 'Onions and shallots']
 ['Chillies and peppers' 'Chillies and peppers']
 ['Tea leaves' 'Cucumbers and gherkins']
 ['Cloves' 'Beans']
 ['Potatoes' 'Cucumbers and gherkins']
 ['Tomatoes' 'Cucumbers and gherkins']
 ['Beans' 'Tomatoes']
 ['Tea leaves' 'Tea leaves']
 ['Tomatoes' 'Tomatoes']
 ['Cloves' 'Cloves']
 ['Beans' 'Beans']
 ['Chillies and peppers' 'Chillies and peppers']
 ['Carrots and turnips' 'Beans']
 ['Cinnamon and cinnamon-tree flowers'
  'Cinnamon and cinnamon-tree flowers']
 ['Beans' 'Beans']
 ['Eggplants' 'Eggplants']
 ['Onions and shallots' 'Onions and shallots']
 ['Vanilla' 'Vanilla']
 ['Pepper' 'Pepper']
 ['Cucumbers and gherkins' 'Cucumbers and gherkins']
 ['Tomatoes' 'Tomatoes']
 ['Tomatoes' 'Tomatoes']
 ['Beans' 'Carrots and turnips']
 ['Pepper' 'Pepper']
 ['Pepper' 'Pepper']
 ['Cinnamon and cinnamon-tree flowers'
  'Cinnamon and cinnamon-tree flowers']
 ['Leeks and other alliaceous vegetables' 'Chillies and peppers']
 ['

In [54]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_actual, y_pred)

print(f"Model Accuracy: {acc:.2%}")

Model Accuracy: 82.14%
